<?php
// index.php
session_start();
// Ensure user is logged in, has changed their password, and is Admin or HR
if (!isset($_SESSION['user_id']) || isset($_SESSION['force_password_change']) || !in_array($_SESSION['role'], ['admin', 'hr'])) {
    header("Location: login.php");
    exit;
}
require_once 'db.php';

// Fetch the latest 1000 records so the datatable has data to paginate and search
$stmt = $pdo->query("
    SELECT a.*, e.name 
    FROM attendance_logs a 
    JOIN employees e ON a.en_no = e.en_no 
    ORDER BY a.record_datetime DESC 
    LIMIT 1000
");
$logs = $stmt->fetchAll();

// Fetch all employees for the Export Dropdown
$empStmt = $pdo->query("SELECT en_no, name FROM employees ORDER BY name ASC");
$employees = $empStmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance System Admin</title>
    
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.tailwindcss.min.css">
</head>
<body class="bg-gray-50 dark:bg-gray-900 antialiased">

    <nav class="bg-white border-b border-gray-200 px-4 py-2.5 dark:bg-gray-800 dark:border-gray-700 fixed left-0 right-0 top-0 z-50">
        <div class="flex flex-wrap justify-between items-center max-w-7xl mx-auto">
            <div class="flex justify-start items-center">
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Time & Attendance</span>
            </div>
            <div class="flex items-center">
                <span class="text-sm text-gray-700 dark:text-gray-300 me-4">Logged in as: <strong><?= htmlspecialchars($_SESSION['username']) ?></strong> (<?= htmlspecialchars($_SESSION['role']) ?>)</span>
                <a href="logout.php" class="text-sm text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-600 font-medium">Logout</a>
            </div>
        </div>
    </nav>

    <main class="p-4 h-auto pt-20 max-w-7xl mx-auto">
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            
            <div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">Import Records</h5>
                <p class="mb-4 text-sm text-gray-700 dark:text-gray-400">Upload the tab-separated .TXT file generated by the biometric terminal.</p>
                
                <form id="uploadForm" class="flex flex-col sm:flex-row items-center gap-3">
                    <input class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" id="file" name="file" type="file" accept=".txt">
                    <button type="submit" class="w-full sm:w-auto text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Import
                    </button>
                </form>
                <div id="alertContainer" class="mt-4 hidden"></div>
            </div>

            <div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">Export Monthly Attendance</h5>
                <p class="mb-4 text-sm text-gray-700 dark:text-gray-400">Download a CSV report for a specific employee and month.</p>
                
                <form action="export.php" method="GET" class="flex flex-col sm:flex-row items-center gap-3">
                    <select name="en_no" required class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <option value="" disabled selected>Select Employee</option>
                        <?php foreach ($employees as $emp): ?>
                            <option value="<?= $emp['en_no'] ?>"><?= htmlspecialchars($emp['name']) ?> (ID: <?= $emp['en_no'] ?>)</option>
                        <?php endforeach; ?>
                    </select>

                    <input type="month" name="month" required class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full sm:w-auto p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    
                    <button type="submit" class="w-full sm:w-auto text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">
                        Export
                    </button>
                </form>
            </div>

        </div>

        <div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <h5 class="mb-4 text-xl font-bold tracking-tight text-gray-900 dark:text-white">System Logs</h5>
            
            <div class="overflow-x-auto">
                <table id="attendanceTable" class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                    <thead class="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            <th scope="col" class="px-6 py-3">EnNo</th>
                            <th scope="col" class="px-6 py-3">Name</th>
                            <th scope="col" class="px-6 py-3">Date & Time</th>
                            <th scope="col" class="px-6 py-3">Type (IN/OUT)</th>
                            <th scope="col" class="px-6 py-3">Mode</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($logs as $log): ?>
                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-6 py-4"><?= htmlspecialchars($log['en_no']) ?></td>
                            <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                <?= htmlspecialchars($log['name']) ?>
                            </td>
                            <td class="px-6 py-4" data-sort="<?= strtotime($log['record_datetime']) ?>">
                                <?= date('M d, Y h:i A', strtotime($log['record_datetime'])) ?>
                            </td>
                            <td class="px-6 py-4">
                                <?php if ($log['in_out'] == 0): ?>
                                    <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">Duty On (0)</span>
                                <?php else: ?>
                                    <span class="bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">Duty Off (<?= htmlspecialchars($log['in_out']) ?>)</span>
                                <?php endif; ?>
                            </td>
                            <td class="px-6 py-4"><?= htmlspecialchars($log['mode']) ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
    
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.tailwindcss.min.js"></script>

    <script>
        // Initialize DataTable
        $(document).ready(function() {
            $('#attendanceTable').DataTable({
                "pageLength": 10, // Default rows per page
                "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]], // Selectable row counts
                "order": [[2, "desc"]], // Default sort by Date & Time column (index 2) descending
                "language": {
                    "search": "Filter records:",
                    "lengthMenu": "Show _MENU_ entries per page"
                }
            });
        });

        // File Upload Logic
        document.getElementById('uploadForm').addEventListener('submit', async function(e) {
            e.preventDefault();
            
            const fileInput = document.getElementById('file');
            const alertContainer = document.getElementById('alertContainer');
            
            if(fileInput.files.length === 0) {
                showAlert('error', 'Please select a file first.');
                return;
            }

            const formData = new FormData();
            formData.append('file', fileInput.files[0]);

            try {
                const response = await fetch('import.php', {
                    method: 'POST',
                    body: formData
                });
                
                const result = await response.json();
                
                if(result.status === 'success') {
                    showAlert('success', result.message);
                    setTimeout(() => location.reload(), 1500); 
                } else {
                    showAlert('error', result.message);
                }
            } catch (error) {
                showAlert('error', 'An unexpected error occurred during the upload.');
            }
        });

        function showAlert(type, message) {
            const container = document.getElementById('alertContainer');
            container.classList.remove('hidden');
            
            const colorClass = type === 'success' ? 'text-green-800 bg-green-50 dark:bg-gray-800 dark:text-green-400' : 'text-red-800 bg-red-50 dark:bg-gray-800 dark:text-red-400';
            
            container.innerHTML = `
                <div class="p-4 mb-4 text-sm rounded-lg ${colorClass}" role="alert">
                    <span class="font-medium">${type === 'success' ? 'Success!' : 'Error!'}</span> ${message}
                </div>
            `;
        }
    </script>
</body>
</html>